//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Windows.Forms.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Windows.Forms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;XCoolForm&gt;
        ///   &lt;XCoolFormElements&gt;
        ///      &lt;TitleBar&gt;
        ///	&lt;InnerBorderColor r=&quot;64&quot; g=&quot;64&quot; b=&quot;65&quot;&gt;&lt;/InnerBorderColor&gt;
        ///	&lt;OuterBorderColor r=&quot;79&quot; g=&quot;79&quot; b=&quot;80&quot;&gt;&lt;/OuterBorderColor&gt;
        ///        &lt;TitleBarCaptionColor r=&quot;255&quot; g=&quot;255&quot; b=&quot;255&quot;&gt; &lt;/TitleBarCaptionColor&gt;
        ///	&lt;ButtonBox&gt;
        ///    &lt;MixColor1 r=&quot;84&quot; g=&quot;84&quot; b=&quot;85&quot;&gt; &lt;/MixColor1&gt;
        ///    &lt;MixColor2 r=&quot;103&quot; g=&quot;103&quot; b=&quot;104&quot;&gt; &lt;/MixColor2&gt;
        ///    &lt;MixColor3 r=&quot;103&quot; g=&quot;103&quot; b=&quot;104&quot;&gt; &lt;/MixColor3&gt;
        ///    &lt;MixColor4 r=&quot;103&quot; g=&quot;103&quot; b=&quot;104&quot;&gt; &lt;/MixColor4&gt;
        ///    &lt;MixColor5 r=&quot;63&quot; g=&quot;63&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AdobeMediaPlayerTheme {
            get {
                return ResourceManager.GetString("AdobeMediaPlayerTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;XCoolForm&gt;
        ///   &lt;XCoolFormElements&gt;
        ///      &lt;TitleBar&gt;
        ///	&lt;InnerBorderColor r=&quot;143&quot; g=&quot;217&quot; b=&quot;69&quot;&gt;&lt;/InnerBorderColor&gt;
        ///	&lt;OuterBorderColor r=&quot;103&quot; g=&quot;166&quot; b=&quot;51&quot;&gt;&lt;/OuterBorderColor&gt;
        ///        &lt;TitleBarCaptionColor r=&quot;4&quot; g=&quot;4&quot; b=&quot;4&quot;&gt; &lt;/TitleBarCaptionColor&gt;
        ///	&lt;ButtonBox&gt;    
        ///            &lt;MixColor1 r=&quot;218&quot; g=&quot;242&quot; b=&quot;22&quot;&gt; &lt;/MixColor1&gt;
        ///	    &lt;MixColor2 r=&quot;135&quot; g=&quot;197&quot; b=&quot;26&quot;&gt; &lt;/MixColor2&gt;
        ///	    &lt;MixColor3 r=&quot;104&quot; g=&quot;171&quot; b=&quot;29&quot;&gt; &lt;/MixColor3&gt;
        ///	    &lt;MixColor4 r=&quot;65&quot; g=&quot;138&quot; b=&quot;20&quot;&gt; &lt;/MixColor4&gt;
        ///	    &lt;MixColor5 r [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AlienTheme {
            get {
                return ResourceManager.GetString("AlienTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;XCoolForm&gt;
        ///   &lt;XCoolFormElements&gt;
        ///      &lt;TitleBar&gt;
        ///	&lt;InnerBorderColor r=&quot;212&quot; g=&quot;207&quot; b=&quot;53&quot;&gt;&lt;/InnerBorderColor&gt;
        ///	&lt;OuterBorderColor r=&quot;5&quot; g=&quot;5&quot; b=&quot;5&quot;&gt;&lt;/OuterBorderColor&gt;
        ///        &lt;TitleBarCaptionColor r=&quot;0&quot; g=&quot;0&quot; b=&quot;0&quot;&gt; &lt;/TitleBarCaptionColor&gt;
        ///	&lt;ButtonBox&gt;    
        ///            &lt;MixColor1 r=&quot;255&quot; g=&quot;233&quot; b=&quot;15&quot;&gt; &lt;/MixColor1&gt;
        ///	    &lt;MixColor2 r=&quot;255&quot; g=&quot;233&quot; b=&quot;15&quot;&gt; &lt;/MixColor2&gt;
        ///	    &lt;MixColor3 r=&quot;239&quot; g=&quot;92&quot; b=&quot;40&quot;&gt; &lt;/MixColor3&gt;
        ///	    &lt;MixColor4 r=&quot;203&quot; g=&quot;41&quot; b=&quot;36&quot;&gt; &lt;/MixColor4&gt;
        ///	    &lt;MixColor5 r=&quot;255&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AnimalKingdomTheme {
            get {
                return ResourceManager.GetString("AnimalKingdomTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;XCoolForm&gt;
        ///   &lt;XCoolFormElements&gt;
        ///      &lt;TitleBar&gt;
        ///	&lt;InnerBorderColor r=&quot;70&quot; g=&quot;70&quot; b=&quot;70&quot;&gt;&lt;/InnerBorderColor&gt;
        ///	&lt;OuterBorderColor r=&quot;0&quot; g=&quot;0&quot; b=&quot;0&quot;&gt;&lt;/OuterBorderColor&gt;
        ///        &lt;TitleBarCaptionColor r=&quot;255&quot; g=&quot;255&quot; b=&quot;255&quot;&gt; &lt;/TitleBarCaptionColor&gt;
        ///	&lt;ButtonBox&gt;
        ///            &lt;MixColor1 r=&quot;20&quot; g=&quot;20&quot; b=&quot;20&quot;&gt; &lt;/MixColor1&gt;
        ///            &lt;MixColor2 r=&quot;42&quot; g=&quot;42&quot; b=&quot;42&quot;&gt; &lt;/MixColor2&gt;
        ///            &lt;MixColor3 r=&quot;11&quot; g=&quot;11&quot; b=&quot;11&quot;&gt; &lt;/MixColor3&gt;
        ///            &lt;MixColor4 r=&quot;40&quot; g=&quot;40&quot; b=&quot;40&quot;&gt; &lt;/MixColor4&gt;
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlackTheme {
            get {
                return ResourceManager.GetString("BlackTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;XCoolForm&gt;
        ///   &lt;XCoolFormElements&gt;
        ///      &lt;TitleBar&gt;
        ///	&lt;InnerBorderColor r=&quot;246&quot; g=&quot;244&quot; b=&quot;252&quot;&gt;&lt;/InnerBorderColor&gt;
        ///	&lt;OuterBorderColor r=&quot;154&quot; g=&quot;174&quot; b=&quot;213&quot;&gt;&lt;/OuterBorderColor&gt;
        ///        &lt;TitleBarCaptionColor r=&quot;62&quot; g=&quot;106&quot; b=&quot;170&quot;&gt; &lt;/TitleBarCaptionColor&gt;
        ///	&lt;ButtonBox&gt;    
        ///            &lt;MixColor1 r=&quot;227&quot; g=&quot;235&quot; b=&quot;247&quot;&gt; &lt;/MixColor1&gt;
        ///	    &lt;MixColor2 r=&quot;221&quot; g=&quot;234&quot; b=&quot;251&quot;&gt; &lt;/MixColor2&gt;
        ///	    &lt;MixColor3 r=&quot;205&quot; g=&quot;224&quot; b=&quot;248&quot;&gt; &lt;/MixColor3&gt;
        ///	    &lt;MixColor4 r=&quot;217&quot; g=&quot;232&quot; b=&quot;250&quot;&gt; &lt;/MixColor4&gt;
        ///	     [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueWinterTheme {
            get {
                return ResourceManager.GetString("BlueWinterTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;XCoolForm&gt;
        ///   &lt;XCoolFormElements&gt;
        ///      &lt;TitleBar&gt;
        ///	&lt;InnerBorderColor r=&quot;11&quot; g=&quot;16&quot; b=&quot;19&quot;&gt;&lt;/InnerBorderColor&gt;
        ///	&lt;OuterBorderColor r=&quot;66&quot; g=&quot;70&quot; b=&quot;82&quot;&gt;&lt;/OuterBorderColor&gt;
        ///        &lt;TitleBarCaptionColor r=&quot;186&quot; g=&quot;181&quot; b=&quot;159&quot;&gt; &lt;/TitleBarCaptionColor&gt;
        ///	&lt;ButtonBox&gt;    
        ///            &lt;MixColor1 r=&quot;171&quot; g=&quot;171&quot; b=&quot;171&quot;&gt; &lt;/MixColor1&gt;
        ///	    &lt;MixColor2 r=&quot;42&quot; g=&quot;42&quot; b=&quot;42&quot;&gt; &lt;/MixColor2&gt;
        ///	    &lt;MixColor3 r=&quot;11&quot; g=&quot;11&quot; b=&quot;11&quot;&gt; &lt;/MixColor3&gt;
        ///	    &lt;MixColor4 r=&quot;40&quot; g=&quot;40&quot; b=&quot;40&quot;&gt; &lt;/MixColor4&gt;
        ///	    &lt;MixColor5 r=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DarkSystemTheme {
            get {
                return ResourceManager.GetString("DarkSystemTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;XCoolForm&gt;
        ///   &lt;XCoolFormElements&gt;
        ///      &lt;TitleBar&gt;
        ///	&lt;InnerBorderColor r=&quot;113&quot; g=&quot;112&quot; b=&quot;110&quot;&gt;&lt;/InnerBorderColor&gt;
        ///	&lt;OuterBorderColor r=&quot;160&quot; g=&quot;160&quot; b=&quot;160&quot;&gt;&lt;/OuterBorderColor&gt;
        ///        &lt;TitleBarCaptionColor r=&quot;4&quot; g=&quot;4&quot; b=&quot;4&quot;&gt; &lt;/TitleBarCaptionColor&gt;
        ///	&lt;ButtonBox&gt;
        ///    &lt;MixColor1 r=&quot;183&quot; g=&quot;203&quot; b=&quot;236&quot;&gt; &lt;/MixColor1&gt;
        ///    &lt;MixColor2 r=&quot;149&quot; g=&quot;193&quot; b=&quot;228&quot;&gt; &lt;/MixColor2&gt;
        ///    &lt;MixColor3 r=&quot;159&quot; g=&quot;221&quot; b=&quot;255&quot;&gt; &lt;/MixColor3&gt;
        ///    &lt;MixColor4 r=&quot;159&quot; g=&quot;221&quot; b=&quot;255&quot;&gt; &lt;/MixColor4&gt;
        ///    &lt;MixColor5 r=&quot;159&quot; g= [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MacOSTheme {
            get {
                return ResourceManager.GetString("MacOSTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;XCoolForm&gt;
        ///   &lt;XCoolFormElements&gt;
        ///      &lt;TitleBar&gt;
        ///	&lt;InnerBorderColor r=&quot;212&quot; g=&quot;208&quot; b=&quot;200&quot;&gt;&lt;/InnerBorderColor&gt;
        ///	&lt;OuterBorderColor r=&quot;200&quot; g=&quot;200&quot; b=&quot;200&quot;&gt;&lt;/OuterBorderColor&gt;
        ///        &lt;TitleBarCaptionColor r=&quot;255&quot; g=&quot;255&quot; b=&quot;255&quot;&gt; &lt;/TitleBarCaptionColor&gt;
        ///	&lt;ButtonBox&gt;    
        ///            &lt;MixColor1 r=&quot;255&quot; g=&quot;255&quot; b=&quot;255&quot;&gt; &lt;/MixColor1&gt;
        ///	    &lt;MixColor2 r=&quot;212&quot; g=&quot;208&quot; b=&quot;200&quot;&gt; &lt;/MixColor2&gt;
        ///	    &lt;MixColor3 r=&quot;212&quot; g=&quot;208&quot; b=&quot;200&quot;&gt; &lt;/MixColor3&gt;
        ///	    &lt;MixColor4 r=&quot;212&quot; g=&quot;208&quot; b=&quot;200&quot;&gt; &lt;/MixColor4&gt;
        ///	    [rest of string was truncated]&quot;;.
        /// </summary>
        public static string StandardWindowsTheme {
            get {
                return ResourceManager.GetString("StandardWindowsTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;XCoolForm&gt;
        ///   &lt;XCoolFormElements&gt;
        ///      &lt;TitleBar&gt;
        ///	&lt;InnerBorderColor r=&quot;204&quot; g=&quot;155&quot; b=&quot;180&quot;&gt;&lt;/InnerBorderColor&gt;
        ///	&lt;OuterBorderColor r=&quot;222&quot; g=&quot;198&quot; b=&quot;214&quot;&gt;&lt;/OuterBorderColor&gt;
        ///        &lt;TitleBarCaptionColor r=&quot;140&quot; g=&quot;90&quot; b=&quot;107&quot;&gt; &lt;/TitleBarCaptionColor&gt;
        ///	&lt;ButtonBox&gt;    
        ///            &lt;MixColor1 r=&quot;231&quot; g=&quot;214&quot; b=&quot;222&quot;&gt; &lt;/MixColor1&gt;
        ///	    &lt;MixColor2 r=&quot;206&quot; g=&quot;165&quot; b=&quot;189&quot;&gt; &lt;/MixColor2&gt;
        ///	    &lt;MixColor3 r=&quot;204&quot; g=&quot;155&quot; b=&quot;160&quot;&gt; &lt;/MixColor3&gt;
        ///	    &lt;MixColor4 r=&quot;214&quot; g=&quot;155&quot; b=&quot;180&quot;&gt; &lt;/MixColor4&gt;
        ///	     [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ValentineTheme {
            get {
                return ResourceManager.GetString("ValentineTheme", resourceCulture);
            }
        }
        
        public static byte[] visitor2 {
            get {
                object obj = ResourceManager.GetObject("visitor2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;XCoolForm&gt;
        ///   &lt;XCoolFormElements&gt;
        ///      &lt;TitleBar&gt;
        ///	&lt;InnerBorderColor r=&quot;158&quot; g=&quot;158&quot; b=&quot;158&quot;&gt;&lt;/InnerBorderColor&gt;
        ///	&lt;OuterBorderColor r=&quot;29&quot; g=&quot;29&quot; b=&quot;29&quot;&gt;&lt;/OuterBorderColor&gt;
        ///        &lt;TitleBarCaptionColor r=&quot;255&quot; g=&quot;255&quot; b=&quot;255&quot;&gt; &lt;/TitleBarCaptionColor&gt;
        ///	&lt;ButtonBox&gt;
        ///    &lt;MixColor1 r=&quot;74&quot; g=&quot;74&quot; b=&quot;74&quot;&gt; &lt;/MixColor1&gt;
        ///    &lt;MixColor2 r=&quot;104&quot; g=&quot;104&quot; b=&quot;104&quot;&gt; &lt;/MixColor2&gt;
        ///    &lt;MixColor3 r=&quot;106&quot; g=&quot;106&quot; b=&quot;106&quot;&gt; &lt;/MixColor3&gt;
        ///    &lt;MixColor4 r=&quot;142&quot; g=&quot;142&quot; b=&quot;142&quot;&gt; &lt;/MixColor4&gt;
        ///    &lt;MixColor5 r=&quot;150&quot; g= [rest of string was truncated]&quot;;.
        /// </summary>
        public static string VistaTheme {
            get {
                return ResourceManager.GetString("VistaTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;XCoolForm&gt;
        ///   &lt;XCoolFormElements&gt;
        ///      &lt;TitleBar&gt;
        ///	      &lt;InnerBorderColor r=&quot;204&quot; g=&quot;204&quot; b=&quot;204&quot;&gt;&lt;/InnerBorderColor&gt;
        ///	      &lt;OuterBorderColor r=&quot;255&quot; g=&quot;255&quot; b=&quot;255&quot;&gt;&lt;/OuterBorderColor&gt;
        ///        &lt;TitleBarCaptionColor r=&quot;4&quot; g=&quot;4&quot; b=&quot;4&quot;&gt; &lt;/TitleBarCaptionColor&gt;
        ///	      &lt;ButtonBox&gt;
        ///            &lt;MixColor1 r=&quot;245&quot; g=&quot;245&quot; b=&quot;245&quot;&gt; &lt;/MixColor1&gt;
        ///            &lt;MixColor2 r=&quot;243&quot; g=&quot;243&quot; b=&quot;243&quot;&gt; &lt;/MixColor2&gt;
        ///            &lt;MixColor3 r=&quot;254&quot; g=&quot;254&quot; b=&quot;254&quot;&gt; &lt;/MixColor3&gt;
        ///            &lt;MixColor4 r=&quot;253&quot; g=&quot;253 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WhiteTheme {
            get {
                return ResourceManager.GetString("WhiteTheme", resourceCulture);
            }
        }
    }
}
