USE [master]
GO
/****** Object:  Database [PTFLocal]    Script Date: 02/20/2013 17:15:09 ******/
CREATE DATABASE [PTFLocal] ON  PRIMARY 
( NAME = N'PTFLocal', FILENAME = N'e:\DATA\PTFLocal.mdf' , SIZE = 57344KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'PTFLocal_log', FILENAME = N'e:\DATA\PTFLocal_log.ldf' , SIZE = 2560KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [PTFLocal] SET COMPATIBILITY_LEVEL = 100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PTFLocal].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [PTFLocal] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [PTFLocal] SET ANSI_NULLS OFF
GO
ALTER DATABASE [PTFLocal] SET ANSI_PADDING OFF
GO
ALTER DATABASE [PTFLocal] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [PTFLocal] SET ARITHABORT OFF
GO
ALTER DATABASE [PTFLocal] SET AUTO_CLOSE ON
GO
ALTER DATABASE [PTFLocal] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [PTFLocal] SET AUTO_SHRINK ON
GO
ALTER DATABASE [PTFLocal] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [PTFLocal] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [PTFLocal] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [PTFLocal] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [PTFLocal] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [PTFLocal] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [PTFLocal] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [PTFLocal] SET  ENABLE_BROKER
GO
ALTER DATABASE [PTFLocal] SET AUTO_UPDATE_STATISTICS_ASYNC ON
GO
ALTER DATABASE [PTFLocal] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [PTFLocal] SET TRUSTWORTHY OFF
GO
ALTER DATABASE [PTFLocal] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO
ALTER DATABASE [PTFLocal] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [PTFLocal] SET READ_COMMITTED_SNAPSHOT OFF
GO
ALTER DATABASE [PTFLocal] SET HONOR_BROKER_PRIORITY OFF
GO
ALTER DATABASE [PTFLocal] SET  READ_WRITE
GO
ALTER DATABASE [PTFLocal] SET RECOVERY SIMPLE
GO
ALTER DATABASE [PTFLocal] SET  MULTI_USER
GO
ALTER DATABASE [PTFLocal] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [PTFLocal] SET DB_CHAINING OFF
GO
EXEC sys.sp_db_vardecimal_storage_format N'PTFLocal', N'ON'
GO
USE [PTFLocal]
GO
/****** Object:  User [NT AUTHORITY\SYSTEM]    Script Date: 02/20/2013 17:15:10 ******/
CREATE USER [NT AUTHORITY\SYSTEM] FOR LOGIN [NT AUTHORITY\SYSTEM] WITH DEFAULT_SCHEMA=[dbo]
GO
/****** Object:  User [FINTRAX\GG_TRS_DBAs]    Script Date: 02/20/2013 17:15:10 ******/
CREATE USER [FINTRAX\GG_TRS_DBAs] FOR LOGIN [FINTRAX\GG_TRS_DBAs]
GO
/****** Object:  User [FINTRAX\GG_SQL_Admins_ALL]    Script Date: 02/20/2013 17:15:10 ******/
CREATE USER [FINTRAX\GG_SQL_Admins_ALL] FOR LOGIN [FINTRAX\GG_SQL_Admins_ALL]
GO
/****** Object:  User [BUILTIN\Administrators]    Script Date: 02/20/2013 17:15:10 ******/
CREATE USER [BUILTIN\Administrators] FOR LOGIN [BUILTIN\Administrators]
GO
/****** Object:  Table [dbo].[TMP]    Script Date: 02/20/2013 17:15:11 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TMP](
	[ID] [uniqueidentifier] NOT NULL,
	[DATA] [varbinary](8000) NULL,
	[LENGTH] [int] NULL,
 CONSTRAINT [PK_TMP] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[MESSAGES]    Script Date: 02/20/2013 17:15:11 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MESSAGES](
	[MessageID] [int] IDENTITY(1,1) NOT NULL,
	[Message] [nvarchar](1024) NOT NULL,
	[Source] [int] NOT NULL,
	[Type] [int] NOT NULL,
	[StackTrace] [nvarchar](max) NULL,
	[DateInserted] [datetime] NOT NULL,
	[DateExported] [datetime] NULL,
 CONSTRAINT [PK__MESSAGES__C87C037C07020F21] PRIMARY KEY CLUSTERED 
(
	[MessageID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[FILES]    Script Date: 02/20/2013 17:15:11 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[FILES](
	[FileID] [int] IDENTITY(1,1) NOT NULL,
	[CountryID] [int] NULL,
	[RetailerID] [int] NULL,
	[VoucherID] [nvarchar](30) NULL,
	[SiteCode] [nvarchar](50) NOT NULL,
	[BarCode] [nvarchar](100) NULL,
	[VoucherImage] [varbinary](max) NULL,
	[BarCodeImage] [varbinary](max) NULL,
	[DateInserted] [datetime] NULL,
	[DateExported] [datetime] NULL,
	[DateAllocated] [datetime] NOT NULL,
	[Comment] [nvarchar](max) NULL,
 CONSTRAINT [PK_FILES] PRIMARY KEY CLUSTERED 
(
	[FileID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[CONFIG]    Script Date: 02/20/2013 17:15:11 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CONFIG](
	[ConfigID] [int] IDENTITY(1,1) NOT NULL,
	[Key] [nvarchar](100) NOT NULL,
	[Value] [varbinary](max) NULL,
	[Source] [nvarchar](100) NULL,
 CONSTRAINT [PK__CONFIG__C3BC333C0519C6AF] PRIMARY KEY CLUSTERED 
(
	[ConfigID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
