//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizTalkFiles.Properties {
    using System;
    
    

    partial class Resources {
        
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Deleket_Adobe_Cs4_File_Adobe_Dreamweaver_XML_01 {
            get {
                object obj = ResourceManager.GetObject("Deleket_Adobe_Cs4_File_Adobe_Dreamweaver_XML_01", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
