//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteCodeTest.Proxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Proxy.ISiteCode")]
    public interface ISiteCode {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiteCode/GetLocation", ReplyAction="http://tempuri.org/ISiteCode/GetLocationResponse")]
        SiteCodeLib.Location GetLocation(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiteCode/GetShortCode", ReplyAction="http://tempuri.org/ISiteCode/GetShortCodeResponse")]
        string GetShortCode(string countryCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiteCode/GetInfo", ReplyAction="http://tempuri.org/ISiteCode/GetInfoResponse")]
        string GetInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiteCode/SaveCommand", ReplyAction="http://tempuri.org/ISiteCode/SaveCommandResponse")]
        void SaveCommand();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISiteCodeChannel : SiteCodeTest.Proxy.ISiteCode, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SiteCodeClient : System.ServiceModel.ClientBase<SiteCodeTest.Proxy.ISiteCode>, SiteCodeTest.Proxy.ISiteCode {
        
        public SiteCodeClient() {
        }
        
        public SiteCodeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SiteCodeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SiteCodeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SiteCodeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SiteCodeLib.Location GetLocation(string code) {
            return base.Channel.GetLocation(code);
        }
        
        public string GetShortCode(string countryCode) {
            return base.Channel.GetShortCode(countryCode);
        }
        
        public string GetInfo() {
            return base.Channel.GetInfo();
        }
        
        public void SaveCommand() {
            base.Channel.SaveCommand();
        }
    }
}
