//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPrintTest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VPrintTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--Generated by SWIFTStandards Workstation (build:R5.1.0.4) on 2006 Sep 08 11:58:39--&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;urn:iso:std:iso:20022:tech:xsd:pain.001.001.02&quot; elementFormDefault=&quot;qualified&quot; targetNamespace=&quot;urn:iso:std:iso:20022:tech:xsd:pain.001.001.02&quot;&gt;
        ///&lt;xs:element name=&quot;Document&quot; type=&quot;Document&quot;/&gt;
        ///&lt;xs:complexType name=&quot;AccountIdentification3Choice&quot;&gt;
        ///&lt;xs:sequence&gt;
        ///&lt;xs:choice&gt;
        ///&lt;xs:element name=&quot;IBAN&quot; type=&quot;IBANIdentifier&quot;/&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pain_001_001_02 {
            get {
                return ResourceManager.GetString("pain_001_001_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;no&quot;?&gt;
        ///&lt;!--Generated by SWIFTStandards Workstation (build:R6.1.0.2) on 2009 Jan 08 17:30:53--&gt;
        ///&lt;xs:schema xmlns=&quot;urn:iso:std:iso:20022:tech:xsd:pain.001.001.03&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; elementFormDefault=&quot;qualified&quot; targetNamespace=&quot;urn:iso:std:iso:20022:tech:xsd:pain.001.001.03&quot;&gt;
        ///    &lt;xs:element name=&quot;Document&quot; type=&quot;Document&quot;/&gt;
        ///    &lt;xs:complexType name=&quot;AccountIdentification4Choice&quot;&gt;
        ///        &lt;xs:sequence&gt;
        ///            &lt;xs:choice&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pain_001_001_03 {
            get {
                return ResourceManager.GetString("pain_001_001_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--Generated by SWIFTStandards Workstation (build:R5.1.0.4) on 2006 Sep 08 11:58:39--&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;urn:iso:std:iso:20022:tech:xsd:pain.008.001.01&quot; elementFormDefault=&quot;qualified&quot; targetNamespace=&quot;urn:iso:std:iso:20022:tech:xsd:pain.008.001.01&quot;&gt;
        ///&lt;xs:element name=&quot;Document&quot; type=&quot;Document&quot;/&gt;
        ///&lt;xs:complexType name=&quot;AccountIdentification3Choice&quot;&gt;
        ///&lt;xs:sequence&gt;
        ///&lt;xs:choice&gt;
        ///&lt;xs:element name=&quot;IBAN&quot; type=&quot;IBANIdentifier&quot;/&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pain_008_001_01 {
            get {
                return ResourceManager.GetString("pain_008_001_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;no&quot;?&gt;
        ///&lt;!--Generated by SWIFTStandards Workstation (build:R6.1.0.2) on 2009 Jan 08 17:30:53--&gt;
        ///&lt;xs:schema xmlns=&quot;urn:iso:std:iso:20022:tech:xsd:pain.008.001.02&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; elementFormDefault=&quot;qualified&quot; targetNamespace=&quot;urn:iso:std:iso:20022:tech:xsd:pain.008.001.02&quot;&gt;
        ///    &lt;xs:element name=&quot;Document&quot; type=&quot;Document&quot;/&gt;
        ///    &lt;xs:complexType name=&quot;AccountIdentification4Choice&quot;&gt;
        ///        &lt;xs:sequence&gt;
        ///            &lt;xs:choice&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pain_008_001_02 {
            get {
                return ResourceManager.GetString("pain_008_001_02", resourceCulture);
            }
        }
    }
}
