//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PremierTaxFree.PTFLib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PremierTaxFree.PTFLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER LOGIN sa ENABLE;
        ///GO
        ///ALTER LOGIN sa WITH PASSWORD = &apos;{0}&apos;;
        ///GO.
        /// </summary>
        internal static string EnableSA {
            get {
                return ResourceManager.GetString("EnableSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE MASTER
        ///DECLARE @DBNAME SYSNAME
        ///SET @DBNAME = &apos;PTFLocal&apos;
        ///
        ///DECLARE @ERRORMESSAGE NVARCHAR(1000)
        ///
        ///IF EXISTS(SELECT 1 FROM SYS.DATABASES WHERE DATABASE_ID = DB_ID(@DBNAME) AND IS_BROKER_ENABLED = 0)
        ///BEGIN
        ///	IF EXISTS (SELECT 1 FROM SYS.SYSPROCESSES WHERE DBID = DB_ID(@DBNAME) AND SPID &lt;&gt; @@SPID AND STATUS &lt;&gt; &apos;background&apos;)
        ///	BEGIN
        ///		DECLARE @SPID INT
        ///		
        ///		DECLARE KILLPROCESSES_CURSOR CURSOR FOR 
        ///		SELECT SPID FROM SYS.SYSPROCESSES WHERE DBID = DB_ID(@DBNAME) AND SPID &lt;&gt; @@SPID AND STATUS &lt;&gt; &apos;backg [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EnableServiceBroker {
            get {
                return ResourceManager.GetString("EnableServiceBroker", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap NA {
            get {
                object obj = ResourceManager.GetObject("NA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
