#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FintraxPTFImages.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PTF_Images")]
	public partial class PTFImagesDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertVoucher(Voucher instance);
    partial void UpdateVoucher(Voucher instance);
    partial void DeleteVoucher(Voucher instance);
    partial void InsertUserActivityHistory(UserActivityHistory instance);
    partial void UpdateUserActivityHistory(UserActivityHistory instance);
    partial void DeleteUserActivityHistory(UserActivityHistory instance);
    #endregion
		
		public PTFImagesDataDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["PTF_ImagesConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PTFImagesDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PTFImagesDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PTFImagesDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PTFImagesDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Voucher> Vouchers
		{
			get
			{
				return this.GetTable<Voucher>();
			}
		}
		
		public System.Data.Linq.Table<UserActivityHistory> UserActivityHistories
		{
			get
			{
				return this.GetTable<UserActivityHistory>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Voucher")]
	public partial class Voucher : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _job_id;
		
		private int _iso_id;
		
		private int _branch_id;
		
		private int _v_number;
		
		private string _sitecode;
		
		private string _barcode;
		
		private System.Nullable<System.DateTime> _scandate;
		
		private string _location;
		
		private System.Nullable<int> _operator_id;
		
		private long _scan_image_size;
		
		private System.Data.Linq.Binary _scan_image;
		
		private string _session_Id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onjob_idChanging(int value);
    partial void Onjob_idChanged();
    partial void Oniso_idChanging(int value);
    partial void Oniso_idChanged();
    partial void Onbranch_idChanging(int value);
    partial void Onbranch_idChanged();
    partial void Onv_numberChanging(int value);
    partial void Onv_numberChanged();
    partial void OnsitecodeChanging(string value);
    partial void OnsitecodeChanged();
    partial void OnbarcodeChanging(string value);
    partial void OnbarcodeChanged();
    partial void OnscandateChanging(System.Nullable<System.DateTime> value);
    partial void OnscandateChanged();
    partial void OnlocationChanging(string value);
    partial void OnlocationChanged();
    partial void Onoperator_idChanging(System.Nullable<int> value);
    partial void Onoperator_idChanged();
    partial void Onscan_image_sizeChanging(long value);
    partial void Onscan_image_sizeChanged();
    partial void Onscan_imageChanging(System.Data.Linq.Binary value);
    partial void Onscan_imageChanged();
    partial void Onsession_IdChanging(string value);
    partial void Onsession_IdChanged();
    #endregion
		
		public Voucher()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job_id", DbType="Int NOT NULL")]
		public int job_id
		{
			get
			{
				return this._job_id;
			}
			set
			{
				if ((this._job_id != value))
				{
					this.Onjob_idChanging(value);
					this.SendPropertyChanging();
					this._job_id = value;
					this.SendPropertyChanged("job_id");
					this.Onjob_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iso_id", DbType="Int NOT NULL")]
		public int iso_id
		{
			get
			{
				return this._iso_id;
			}
			set
			{
				if ((this._iso_id != value))
				{
					this.Oniso_idChanging(value);
					this.SendPropertyChanging();
					this._iso_id = value;
					this.SendPropertyChanged("iso_id");
					this.Oniso_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_branch_id", DbType="Int NOT NULL")]
		public int branch_id
		{
			get
			{
				return this._branch_id;
			}
			set
			{
				if ((this._branch_id != value))
				{
					this.Onbranch_idChanging(value);
					this.SendPropertyChanging();
					this._branch_id = value;
					this.SendPropertyChanged("branch_id");
					this.Onbranch_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_v_number", DbType="Int NOT NULL")]
		public int v_number
		{
			get
			{
				return this._v_number;
			}
			set
			{
				if ((this._v_number != value))
				{
					this.Onv_numberChanging(value);
					this.SendPropertyChanging();
					this._v_number = value;
					this.SendPropertyChanged("v_number");
					this.Onv_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sitecode", DbType="VarChar(10)")]
		public string sitecode
		{
			get
			{
				return this._sitecode;
			}
			set
			{
				if ((this._sitecode != value))
				{
					this.OnsitecodeChanging(value);
					this.SendPropertyChanging();
					this._sitecode = value;
					this.SendPropertyChanged("sitecode");
					this.OnsitecodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_barcode", DbType="VarChar(30)")]
		public string barcode
		{
			get
			{
				return this._barcode;
			}
			set
			{
				if ((this._barcode != value))
				{
					this.OnbarcodeChanging(value);
					this.SendPropertyChanging();
					this._barcode = value;
					this.SendPropertyChanged("barcode");
					this.OnbarcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scandate", DbType="DateTime")]
		public System.Nullable<System.DateTime> scandate
		{
			get
			{
				return this._scandate;
			}
			set
			{
				if ((this._scandate != value))
				{
					this.OnscandateChanging(value);
					this.SendPropertyChanging();
					this._scandate = value;
					this.SendPropertyChanged("scandate");
					this.OnscandateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_location", DbType="VarChar(10)")]
		public string location
		{
			get
			{
				return this._location;
			}
			set
			{
				if ((this._location != value))
				{
					this.OnlocationChanging(value);
					this.SendPropertyChanging();
					this._location = value;
					this.SendPropertyChanged("location");
					this.OnlocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_operator_id", DbType="Int")]
		public System.Nullable<int> operator_id
		{
			get
			{
				return this._operator_id;
			}
			set
			{
				if ((this._operator_id != value))
				{
					this.Onoperator_idChanging(value);
					this.SendPropertyChanging();
					this._operator_id = value;
					this.SendPropertyChanged("operator_id");
					this.Onoperator_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scan_image_size", DbType="BigInt NOT NULL")]
		public long scan_image_size
		{
			get
			{
				return this._scan_image_size;
			}
			set
			{
				if ((this._scan_image_size != value))
				{
					this.Onscan_image_sizeChanging(value);
					this.SendPropertyChanging();
					this._scan_image_size = value;
					this.SendPropertyChanged("scan_image_size");
					this.Onscan_image_sizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scan_image", DbType="VarBinary(MAX) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary scan_image
		{
			get
			{
				return this._scan_image;
			}
			set
			{
				if ((this._scan_image != value))
				{
					this.Onscan_imageChanging(value);
					this.SendPropertyChanging();
					this._scan_image = value;
					this.SendPropertyChanged("scan_image");
					this.Onscan_imageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_session_Id", DbType="VarChar(50)")]
		public string session_Id
		{
			get
			{
				return this._session_Id;
			}
			set
			{
				if ((this._session_Id != value))
				{
					this.Onsession_IdChanging(value);
					this.SendPropertyChanging();
					this._session_Id = value;
					this.SendPropertyChanged("session_Id");
					this.Onsession_IdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserActivityHistory")]
	public partial class UserActivityHistory : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _uahid;
		
		private int _uah_userId;
		
		private int _uah_isoId;
		
		private System.Nullable<System.DateTime> _uah_begin;
		
		private System.Nullable<System.DateTime> _uah_end;
		
		private string _uah_sessionId;
		
		private System.DateTime _createdAt;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuahidChanging(int value);
    partial void OnuahidChanged();
    partial void Onuah_userIdChanging(int value);
    partial void Onuah_userIdChanged();
    partial void Onuah_isoIdChanging(int value);
    partial void Onuah_isoIdChanged();
    partial void Onuah_beginChanging(System.Nullable<System.DateTime> value);
    partial void Onuah_beginChanged();
    partial void Onuah_endChanging(System.Nullable<System.DateTime> value);
    partial void Onuah_endChanged();
    partial void Onuah_sessionIdChanging(string value);
    partial void Onuah_sessionIdChanged();
    partial void OncreatedAtChanging(System.DateTime value);
    partial void OncreatedAtChanged();
    #endregion
		
		public UserActivityHistory()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uahid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int uahid
		{
			get
			{
				return this._uahid;
			}
			set
			{
				if ((this._uahid != value))
				{
					this.OnuahidChanging(value);
					this.SendPropertyChanging();
					this._uahid = value;
					this.SendPropertyChanged("uahid");
					this.OnuahidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uah_userId", DbType="Int NOT NULL")]
		public int uah_userId
		{
			get
			{
				return this._uah_userId;
			}
			set
			{
				if ((this._uah_userId != value))
				{
					this.Onuah_userIdChanging(value);
					this.SendPropertyChanging();
					this._uah_userId = value;
					this.SendPropertyChanged("uah_userId");
					this.Onuah_userIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uah_isoId", DbType="Int NOT NULL")]
		public int uah_isoId
		{
			get
			{
				return this._uah_isoId;
			}
			set
			{
				if ((this._uah_isoId != value))
				{
					this.Onuah_isoIdChanging(value);
					this.SendPropertyChanging();
					this._uah_isoId = value;
					this.SendPropertyChanged("uah_isoId");
					this.Onuah_isoIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uah_begin", DbType="DateTime")]
		public System.Nullable<System.DateTime> uah_begin
		{
			get
			{
				return this._uah_begin;
			}
			set
			{
				if ((this._uah_begin != value))
				{
					this.Onuah_beginChanging(value);
					this.SendPropertyChanging();
					this._uah_begin = value;
					this.SendPropertyChanged("uah_begin");
					this.Onuah_beginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uah_end", DbType="DateTime")]
		public System.Nullable<System.DateTime> uah_end
		{
			get
			{
				return this._uah_end;
			}
			set
			{
				if ((this._uah_end != value))
				{
					this.Onuah_endChanging(value);
					this.SendPropertyChanging();
					this._uah_end = value;
					this.SendPropertyChanged("uah_end");
					this.Onuah_endChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uah_sessionId", DbType="NVarChar(1000)")]
		public string uah_sessionId
		{
			get
			{
				return this._uah_sessionId;
			}
			set
			{
				if ((this._uah_sessionId != value))
				{
					this.Onuah_sessionIdChanging(value);
					this.SendPropertyChanging();
					this._uah_sessionId = value;
					this.SendPropertyChanged("uah_sessionId");
					this.Onuah_sessionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdAt", DbType="DateTime NOT NULL")]
		public System.DateTime createdAt
		{
			get
			{
				return this._createdAt;
			}
			set
			{
				if ((this._createdAt != value))
				{
					this.OncreatedAtChanging(value);
					this.SendPropertyChanging();
					this._createdAt = value;
					this.SendPropertyChanged("createdAt");
					this.OncreatedAtChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
