//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReceivingServiceLib {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ISOs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ISOs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReceivingServiceLib.ISOs", typeof(ISOs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANTARCTICA.
        /// </summary>
        internal static string _10 {
            get {
                return ResourceManager.GetString("_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BULGARIA.
        /// </summary>
        internal static string _100 {
            get {
                return ResourceManager.GetString("_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MYANMAR.
        /// </summary>
        internal static string _104 {
            get {
                return ResourceManager.GetString("_104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BURUNDI.
        /// </summary>
        internal static string _108 {
            get {
                return ResourceManager.GetString("_108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BELARUS.
        /// </summary>
        internal static string _112 {
            get {
                return ResourceManager.GetString("_112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAMBODIA.
        /// </summary>
        internal static string _116 {
            get {
                return ResourceManager.GetString("_116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALGERIA.
        /// </summary>
        internal static string _12 {
            get {
                return ResourceManager.GetString("_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAMEROON.
        /// </summary>
        internal static string _120 {
            get {
                return ResourceManager.GetString("_120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANADA.
        /// </summary>
        internal static string _124 {
            get {
                return ResourceManager.GetString("_124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAPE VERDE.
        /// </summary>
        internal static string _132 {
            get {
                return ResourceManager.GetString("_132", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAYMAN ISLANDS.
        /// </summary>
        internal static string _136 {
            get {
                return ResourceManager.GetString("_136", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CENTRAL AFRICAN REPUBLIC.
        /// </summary>
        internal static string _140 {
            get {
                return ResourceManager.GetString("_140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SRI LANKA.
        /// </summary>
        internal static string _144 {
            get {
                return ResourceManager.GetString("_144", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAD.
        /// </summary>
        internal static string _148 {
            get {
                return ResourceManager.GetString("_148", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHILE.
        /// </summary>
        internal static string _152 {
            get {
                return ResourceManager.GetString("_152", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHINA.
        /// </summary>
        internal static string _156 {
            get {
                return ResourceManager.GetString("_156", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAIWAN.
        /// </summary>
        internal static string _158 {
            get {
                return ResourceManager.GetString("_158", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AMERICAN SAMOA.
        /// </summary>
        internal static string _16 {
            get {
                return ResourceManager.GetString("_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHRISTMAS ISLAND.
        /// </summary>
        internal static string _162 {
            get {
                return ResourceManager.GetString("_162", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COCOS (KEELING) ISLANDS.
        /// </summary>
        internal static string _166 {
            get {
                return ResourceManager.GetString("_166", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COLOMBIA.
        /// </summary>
        internal static string _170 {
            get {
                return ResourceManager.GetString("_170", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMOROS.
        /// </summary>
        internal static string _174 {
            get {
                return ResourceManager.GetString("_174", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAYOTTE.
        /// </summary>
        internal static string _175 {
            get {
                return ResourceManager.GetString("_175", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONGO.
        /// </summary>
        internal static string _178 {
            get {
                return ResourceManager.GetString("_178", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONGO, THE DEMOCRATIC REPUBLIC OF THE.
        /// </summary>
        internal static string _180 {
            get {
                return ResourceManager.GetString("_180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COOK ISLANDS.
        /// </summary>
        internal static string _184 {
            get {
                return ResourceManager.GetString("_184", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COSTA RICA.
        /// </summary>
        internal static string _188 {
            get {
                return ResourceManager.GetString("_188", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CROATIA.
        /// </summary>
        internal static string _191 {
            get {
                return ResourceManager.GetString("_191", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUBA.
        /// </summary>
        internal static string _192 {
            get {
                return ResourceManager.GetString("_192", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CYPRUS.
        /// </summary>
        internal static string _196 {
            get {
                return ResourceManager.GetString("_196", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CYPRUS (NORTH).
        /// </summary>
        internal static string _197 {
            get {
                return ResourceManager.GetString("_197", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANDORRA.
        /// </summary>
        internal static string _20 {
            get {
                return ResourceManager.GetString("_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CZECH REPUBLIC.
        /// </summary>
        internal static string _203 {
            get {
                return ResourceManager.GetString("_203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BENIN.
        /// </summary>
        internal static string _204 {
            get {
                return ResourceManager.GetString("_204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DENMARK.
        /// </summary>
        internal static string _208 {
            get {
                return ResourceManager.GetString("_208", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOMINICA.
        /// </summary>
        internal static string _212 {
            get {
                return ResourceManager.GetString("_212", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOMINICAN REPUBLIC.
        /// </summary>
        internal static string _214 {
            get {
                return ResourceManager.GetString("_214", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ECUADOR.
        /// </summary>
        internal static string _218 {
            get {
                return ResourceManager.GetString("_218", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EL SALVADOR.
        /// </summary>
        internal static string _222 {
            get {
                return ResourceManager.GetString("_222", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EQUATORIAL GUINEA.
        /// </summary>
        internal static string _226 {
            get {
                return ResourceManager.GetString("_226", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETHIOPIA.
        /// </summary>
        internal static string _231 {
            get {
                return ResourceManager.GetString("_231", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERITREA.
        /// </summary>
        internal static string _232 {
            get {
                return ResourceManager.GetString("_232", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESTONIA.
        /// </summary>
        internal static string _233 {
            get {
                return ResourceManager.GetString("_233", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAROE ISLANDS.
        /// </summary>
        internal static string _234 {
            get {
                return ResourceManager.GetString("_234", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FALKLAND ISLANDS (MALVINAS).
        /// </summary>
        internal static string _238 {
            get {
                return ResourceManager.GetString("_238", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS.
        /// </summary>
        internal static string _239 {
            get {
                return ResourceManager.GetString("_239", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANGOLA.
        /// </summary>
        internal static string _24 {
            get {
                return ResourceManager.GetString("_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIJI.
        /// </summary>
        internal static string _242 {
            get {
                return ResourceManager.GetString("_242", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FINLAND.
        /// </summary>
        internal static string _246 {
            get {
                return ResourceManager.GetString("_246", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALAND ISLANDS.
        /// </summary>
        internal static string _248 {
            get {
                return ResourceManager.GetString("_248", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FRANCE DS.
        /// </summary>
        internal static string _250 {
            get {
                return ResourceManager.GetString("_250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FRENCH GUIANA.
        /// </summary>
        internal static string _254 {
            get {
                return ResourceManager.GetString("_254", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FRENCH POLYNESIA.
        /// </summary>
        internal static string _258 {
            get {
                return ResourceManager.GetString("_258", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FRENCH SOUTHERN TERRITORIES.
        /// </summary>
        internal static string _260 {
            get {
                return ResourceManager.GetString("_260", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DJIBOUTI.
        /// </summary>
        internal static string _262 {
            get {
                return ResourceManager.GetString("_262", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GABON.
        /// </summary>
        internal static string _266 {
            get {
                return ResourceManager.GetString("_266", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GEORGIA.
        /// </summary>
        internal static string _268 {
            get {
                return ResourceManager.GetString("_268", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GAMBIA.
        /// </summary>
        internal static string _270 {
            get {
                return ResourceManager.GetString("_270", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PALESTINIAN TERRITORY, OCCUPIED.
        /// </summary>
        internal static string _275 {
            get {
                return ResourceManager.GetString("_275", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GERMANY.
        /// </summary>
        internal static string _276 {
            get {
                return ResourceManager.GetString("_276", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANTIGUA AND BARBUDA.
        /// </summary>
        internal static string _28 {
            get {
                return ResourceManager.GetString("_28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GHANA.
        /// </summary>
        internal static string _288 {
            get {
                return ResourceManager.GetString("_288", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIBRALTAR.
        /// </summary>
        internal static string _292 {
            get {
                return ResourceManager.GetString("_292", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KIRIBATI.
        /// </summary>
        internal static string _296 {
            get {
                return ResourceManager.GetString("_296", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GREECE.
        /// </summary>
        internal static string _300 {
            get {
                return ResourceManager.GetString("_300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GREENLAND.
        /// </summary>
        internal static string _304 {
            get {
                return ResourceManager.GetString("_304", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRENADA.
        /// </summary>
        internal static string _308 {
            get {
                return ResourceManager.GetString("_308", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AZERBAIJAN.
        /// </summary>
        internal static string _31 {
            get {
                return ResourceManager.GetString("_31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUADELOUPE.
        /// </summary>
        internal static string _312 {
            get {
                return ResourceManager.GetString("_312", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUAM.
        /// </summary>
        internal static string _316 {
            get {
                return ResourceManager.GetString("_316", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARGENTINA.
        /// </summary>
        internal static string _32 {
            get {
                return ResourceManager.GetString("_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUATEMALA.
        /// </summary>
        internal static string _320 {
            get {
                return ResourceManager.GetString("_320", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUINEA.
        /// </summary>
        internal static string _324 {
            get {
                return ResourceManager.GetString("_324", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUYANA.
        /// </summary>
        internal static string _328 {
            get {
                return ResourceManager.GetString("_328", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HAITI.
        /// </summary>
        internal static string _332 {
            get {
                return ResourceManager.GetString("_332", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HEARD AND MCDONALD ISLANDS.
        /// </summary>
        internal static string _334 {
            get {
                return ResourceManager.GetString("_334", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOLY SEE (VATICAN CITY STATE).
        /// </summary>
        internal static string _336 {
            get {
                return ResourceManager.GetString("_336", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HONDURAS.
        /// </summary>
        internal static string _340 {
            get {
                return ResourceManager.GetString("_340", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HONG KONG.
        /// </summary>
        internal static string _344 {
            get {
                return ResourceManager.GetString("_344", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HUNGARY.
        /// </summary>
        internal static string _348 {
            get {
                return ResourceManager.GetString("_348", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICELAND.
        /// </summary>
        internal static string _352 {
            get {
                return ResourceManager.GetString("_352", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INDIA.
        /// </summary>
        internal static string _356 {
            get {
                return ResourceManager.GetString("_356", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUSTRALIA.
        /// </summary>
        internal static string _36 {
            get {
                return ResourceManager.GetString("_36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INDONESIA.
        /// </summary>
        internal static string _360 {
            get {
                return ResourceManager.GetString("_360", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IRAN.
        /// </summary>
        internal static string _364 {
            get {
                return ResourceManager.GetString("_364", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IRAQ.
        /// </summary>
        internal static string _368 {
            get {
                return ResourceManager.GetString("_368", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IRELAND.
        /// </summary>
        internal static string _372 {
            get {
                return ResourceManager.GetString("_372", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISRAEL.
        /// </summary>
        internal static string _376 {
            get {
                return ResourceManager.GetString("_376", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ITALY.
        /// </summary>
        internal static string _380 {
            get {
                return ResourceManager.GetString("_380", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IVORY COAST.
        /// </summary>
        internal static string _384 {
            get {
                return ResourceManager.GetString("_384", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JAMAICA.
        /// </summary>
        internal static string _388 {
            get {
                return ResourceManager.GetString("_388", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JAPAN.
        /// </summary>
        internal static string _392 {
            get {
                return ResourceManager.GetString("_392", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KAZAKHSTAN.
        /// </summary>
        internal static string _398 {
            get {
                return ResourceManager.GetString("_398", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AFGHANISTAN.
        /// </summary>
        internal static string _4 {
            get {
                return ResourceManager.GetString("_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUSTRIA.
        /// </summary>
        internal static string _40 {
            get {
                return ResourceManager.GetString("_40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JORDAN.
        /// </summary>
        internal static string _400 {
            get {
                return ResourceManager.GetString("_400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KENYA.
        /// </summary>
        internal static string _404 {
            get {
                return ResourceManager.GetString("_404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KOREA, DEMOCRATIC PEOPLE&apos;S REPUBLIC OF.
        /// </summary>
        internal static string _408 {
            get {
                return ResourceManager.GetString("_408", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KOREA, REPUBLIC OF.
        /// </summary>
        internal static string _410 {
            get {
                return ResourceManager.GetString("_410", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KUWAIT.
        /// </summary>
        internal static string _414 {
            get {
                return ResourceManager.GetString("_414", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KYRGYZSTAN.
        /// </summary>
        internal static string _417 {
            get {
                return ResourceManager.GetString("_417", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAO PEOPLE&apos;S DEMOCRATIC REPUBLIC.
        /// </summary>
        internal static string _418 {
            get {
                return ResourceManager.GetString("_418", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEBANON.
        /// </summary>
        internal static string _422 {
            get {
                return ResourceManager.GetString("_422", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LESOTHO.
        /// </summary>
        internal static string _426 {
            get {
                return ResourceManager.GetString("_426", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LATVIA.
        /// </summary>
        internal static string _428 {
            get {
                return ResourceManager.GetString("_428", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIBERIA.
        /// </summary>
        internal static string _430 {
            get {
                return ResourceManager.GetString("_430", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIBYAN ARAB JAMAHIRIYA.
        /// </summary>
        internal static string _434 {
            get {
                return ResourceManager.GetString("_434", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIECHTENSTEIN.
        /// </summary>
        internal static string _438 {
            get {
                return ResourceManager.GetString("_438", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAHAMAS.
        /// </summary>
        internal static string _44 {
            get {
                return ResourceManager.GetString("_44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LITHUANIA.
        /// </summary>
        internal static string _440 {
            get {
                return ResourceManager.GetString("_440", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LUXEMBOURG.
        /// </summary>
        internal static string _442 {
            get {
                return ResourceManager.GetString("_442", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MACAO.
        /// </summary>
        internal static string _446 {
            get {
                return ResourceManager.GetString("_446", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MADAGASCAR.
        /// </summary>
        internal static string _450 {
            get {
                return ResourceManager.GetString("_450", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MALAWI.
        /// </summary>
        internal static string _454 {
            get {
                return ResourceManager.GetString("_454", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MALAYSIA.
        /// </summary>
        internal static string _458 {
            get {
                return ResourceManager.GetString("_458", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MALDIVES.
        /// </summary>
        internal static string _462 {
            get {
                return ResourceManager.GetString("_462", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MALI.
        /// </summary>
        internal static string _466 {
            get {
                return ResourceManager.GetString("_466", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MALTA.
        /// </summary>
        internal static string _470 {
            get {
                return ResourceManager.GetString("_470", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MARTINIQUE.
        /// </summary>
        internal static string _474 {
            get {
                return ResourceManager.GetString("_474", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAURITANIA.
        /// </summary>
        internal static string _478 {
            get {
                return ResourceManager.GetString("_478", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAHRAIN.
        /// </summary>
        internal static string _48 {
            get {
                return ResourceManager.GetString("_48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAURITIUS.
        /// </summary>
        internal static string _480 {
            get {
                return ResourceManager.GetString("_480", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEXICO.
        /// </summary>
        internal static string _484 {
            get {
                return ResourceManager.GetString("_484", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MONACO.
        /// </summary>
        internal static string _492 {
            get {
                return ResourceManager.GetString("_492", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MONGOLIA.
        /// </summary>
        internal static string _496 {
            get {
                return ResourceManager.GetString("_496", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOLDOVA, REPUBLIC OF.
        /// </summary>
        internal static string _498 {
            get {
                return ResourceManager.GetString("_498", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MONTENEGRO.
        /// </summary>
        internal static string _499 {
            get {
                return ResourceManager.GetString("_499", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BANGLADESH.
        /// </summary>
        internal static string _50 {
            get {
                return ResourceManager.GetString("_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MONTSERRAT.
        /// </summary>
        internal static string _500 {
            get {
                return ResourceManager.GetString("_500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOROCCO.
        /// </summary>
        internal static string _504 {
            get {
                return ResourceManager.GetString("_504", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOZAMBIQUE.
        /// </summary>
        internal static string _508 {
            get {
                return ResourceManager.GetString("_508", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARMENIA.
        /// </summary>
        internal static string _51 {
            get {
                return ResourceManager.GetString("_51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OMAN.
        /// </summary>
        internal static string _512 {
            get {
                return ResourceManager.GetString("_512", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAMIBIA.
        /// </summary>
        internal static string _516 {
            get {
                return ResourceManager.GetString("_516", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BARBADOS.
        /// </summary>
        internal static string _52 {
            get {
                return ResourceManager.GetString("_52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAURU.
        /// </summary>
        internal static string _520 {
            get {
                return ResourceManager.GetString("_520", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEPAL.
        /// </summary>
        internal static string _524 {
            get {
                return ResourceManager.GetString("_524", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NETHERLANDS.
        /// </summary>
        internal static string _528 {
            get {
                return ResourceManager.GetString("_528", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NETHERLANDS ANTILLES.
        /// </summary>
        internal static string _530 {
            get {
                return ResourceManager.GetString("_530", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARUBA.
        /// </summary>
        internal static string _533 {
            get {
                return ResourceManager.GetString("_533", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sint Maarten (Dutch part).
        /// </summary>
        internal static string _534 {
            get {
                return ResourceManager.GetString("_534", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonaire, Sint Eustatius and Saba.
        /// </summary>
        internal static string _535 {
            get {
                return ResourceManager.GetString("_535", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW CALEDONIA.
        /// </summary>
        internal static string _540 {
            get {
                return ResourceManager.GetString("_540", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VANUATU.
        /// </summary>
        internal static string _548 {
            get {
                return ResourceManager.GetString("_548", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW ZEALAND.
        /// </summary>
        internal static string _554 {
            get {
                return ResourceManager.GetString("_554", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NICARAGUA.
        /// </summary>
        internal static string _558 {
            get {
                return ResourceManager.GetString("_558", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BELGIUM.
        /// </summary>
        internal static string _56 {
            get {
                return ResourceManager.GetString("_56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIGER.
        /// </summary>
        internal static string _562 {
            get {
                return ResourceManager.GetString("_562", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIGERIA.
        /// </summary>
        internal static string _566 {
            get {
                return ResourceManager.GetString("_566", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIUE.
        /// </summary>
        internal static string _570 {
            get {
                return ResourceManager.GetString("_570", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NORFOLK ISLAND.
        /// </summary>
        internal static string _574 {
            get {
                return ResourceManager.GetString("_574", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NORWAY.
        /// </summary>
        internal static string _578 {
            get {
                return ResourceManager.GetString("_578", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NORTHERN MARIANA ISLANDS.
        /// </summary>
        internal static string _580 {
            get {
                return ResourceManager.GetString("_580", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNITED STATES MINOR OUTLYING ISLANDS.
        /// </summary>
        internal static string _581 {
            get {
                return ResourceManager.GetString("_581", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MICRONESIA.
        /// </summary>
        internal static string _583 {
            get {
                return ResourceManager.GetString("_583", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MARSHALL ISLANDS.
        /// </summary>
        internal static string _584 {
            get {
                return ResourceManager.GetString("_584", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PALAU.
        /// </summary>
        internal static string _585 {
            get {
                return ResourceManager.GetString("_585", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAKISTAN.
        /// </summary>
        internal static string _586 {
            get {
                return ResourceManager.GetString("_586", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PANAMA.
        /// </summary>
        internal static string _591 {
            get {
                return ResourceManager.GetString("_591", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAPUA NEW GUINEA.
        /// </summary>
        internal static string _598 {
            get {
                return ResourceManager.GetString("_598", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BERMUDA.
        /// </summary>
        internal static string _60 {
            get {
                return ResourceManager.GetString("_60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PARAGUAY.
        /// </summary>
        internal static string _600 {
            get {
                return ResourceManager.GetString("_600", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERU.
        /// </summary>
        internal static string _604 {
            get {
                return ResourceManager.GetString("_604", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHILIPPINES.
        /// </summary>
        internal static string _608 {
            get {
                return ResourceManager.GetString("_608", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PITCAIRN.
        /// </summary>
        internal static string _612 {
            get {
                return ResourceManager.GetString("_612", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POLAND.
        /// </summary>
        internal static string _616 {
            get {
                return ResourceManager.GetString("_616", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PORTUGAL.
        /// </summary>
        internal static string _620 {
            get {
                return ResourceManager.GetString("_620", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUINEA-BISSAU.
        /// </summary>
        internal static string _624 {
            get {
                return ResourceManager.GetString("_624", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMOR-LESTE.
        /// </summary>
        internal static string _626 {
            get {
                return ResourceManager.GetString("_626", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PUERTO RICO.
        /// </summary>
        internal static string _630 {
            get {
                return ResourceManager.GetString("_630", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QATAR.
        /// </summary>
        internal static string _634 {
            get {
                return ResourceManager.GetString("_634", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REUNION.
        /// </summary>
        internal static string _638 {
            get {
                return ResourceManager.GetString("_638", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BHUTAN.
        /// </summary>
        internal static string _64 {
            get {
                return ResourceManager.GetString("_64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROMANIA.
        /// </summary>
        internal static string _642 {
            get {
                return ResourceManager.GetString("_642", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RUSSIAN FEDERATION.
        /// </summary>
        internal static string _643 {
            get {
                return ResourceManager.GetString("_643", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RWANDA.
        /// </summary>
        internal static string _646 {
            get {
                return ResourceManager.GetString("_646", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to St.Barthelemy.
        /// </summary>
        internal static string _652 {
            get {
                return ResourceManager.GetString("_652", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ST. HELENA.
        /// </summary>
        internal static string _654 {
            get {
                return ResourceManager.GetString("_654", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ST. KITTS AND NEVIS.
        /// </summary>
        internal static string _659 {
            get {
                return ResourceManager.GetString("_659", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANGUILLA.
        /// </summary>
        internal static string _660 {
            get {
                return ResourceManager.GetString("_660", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ST. LUCIA.
        /// </summary>
        internal static string _662 {
            get {
                return ResourceManager.GetString("_662", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to St Martin.
        /// </summary>
        internal static string _663 {
            get {
                return ResourceManager.GetString("_663", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ST. PIERRE AND MIQUELON.
        /// </summary>
        internal static string _666 {
            get {
                return ResourceManager.GetString("_666", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ST. VINCENT AND THE GRENADINES.
        /// </summary>
        internal static string _670 {
            get {
                return ResourceManager.GetString("_670", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAN MARINO.
        /// </summary>
        internal static string _674 {
            get {
                return ResourceManager.GetString("_674", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAO TOME AND PRINCIPE.
        /// </summary>
        internal static string _678 {
            get {
                return ResourceManager.GetString("_678", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOLIVIA.
        /// </summary>
        internal static string _68 {
            get {
                return ResourceManager.GetString("_68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAUDI ARABIA.
        /// </summary>
        internal static string _682 {
            get {
                return ResourceManager.GetString("_682", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SENEGAL.
        /// </summary>
        internal static string _686 {
            get {
                return ResourceManager.GetString("_686", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERBIA.
        /// </summary>
        internal static string _688 {
            get {
                return ResourceManager.GetString("_688", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEYCHELLES.
        /// </summary>
        internal static string _690 {
            get {
                return ResourceManager.GetString("_690", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIERRA LEONE.
        /// </summary>
        internal static string _694 {
            get {
                return ResourceManager.GetString("_694", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOSNIA AND HERZEGOWINA.
        /// </summary>
        internal static string _70 {
            get {
                return ResourceManager.GetString("_70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SINGAPORE.
        /// </summary>
        internal static string _702 {
            get {
                return ResourceManager.GetString("_702", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SLOVAKIA.
        /// </summary>
        internal static string _703 {
            get {
                return ResourceManager.GetString("_703", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIETNAM.
        /// </summary>
        internal static string _704 {
            get {
                return ResourceManager.GetString("_704", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SLOVENIA.
        /// </summary>
        internal static string _705 {
            get {
                return ResourceManager.GetString("_705", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOMALIA.
        /// </summary>
        internal static string _706 {
            get {
                return ResourceManager.GetString("_706", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOUTH AFRICA.
        /// </summary>
        internal static string _710 {
            get {
                return ResourceManager.GetString("_710", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIMBABWE.
        /// </summary>
        internal static string _716 {
            get {
                return ResourceManager.GetString("_716", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOTSWANA.
        /// </summary>
        internal static string _72 {
            get {
                return ResourceManager.GetString("_72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPAIN.
        /// </summary>
        internal static string _724 {
            get {
                return ResourceManager.GetString("_724", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUDAN.
        /// </summary>
        internal static string _729 {
            get {
                return ResourceManager.GetString("_729", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WESTERN SAHARA.
        /// </summary>
        internal static string _732 {
            get {
                return ResourceManager.GetString("_732", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO Country.
        /// </summary>
        internal static string _736 {
            get {
                return ResourceManager.GetString("_736", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOUVET ISLAND.
        /// </summary>
        internal static string _74 {
            get {
                return ResourceManager.GetString("_74", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SURINAME.
        /// </summary>
        internal static string _740 {
            get {
                return ResourceManager.GetString("_740", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SVALBARD AND JAN MAYEN.
        /// </summary>
        internal static string _744 {
            get {
                return ResourceManager.GetString("_744", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SWAZILAND.
        /// </summary>
        internal static string _748 {
            get {
                return ResourceManager.GetString("_748", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SWEDEN.
        /// </summary>
        internal static string _752 {
            get {
                return ResourceManager.GetString("_752", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SWITZERLAND.
        /// </summary>
        internal static string _756 {
            get {
                return ResourceManager.GetString("_756", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BRAZIL.
        /// </summary>
        internal static string _76 {
            get {
                return ResourceManager.GetString("_76", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYRIAN ARAB REPUBLIC.
        /// </summary>
        internal static string _760 {
            get {
                return ResourceManager.GetString("_760", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAJIKISTAN.
        /// </summary>
        internal static string _762 {
            get {
                return ResourceManager.GetString("_762", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THAILAND.
        /// </summary>
        internal static string _764 {
            get {
                return ResourceManager.GetString("_764", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOGO.
        /// </summary>
        internal static string _768 {
            get {
                return ResourceManager.GetString("_768", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOKELAU.
        /// </summary>
        internal static string _772 {
            get {
                return ResourceManager.GetString("_772", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TONGA.
        /// </summary>
        internal static string _776 {
            get {
                return ResourceManager.GetString("_776", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRINIDAD AND TOBAGO.
        /// </summary>
        internal static string _780 {
            get {
                return ResourceManager.GetString("_780", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNITED ARAB EMIRATES.
        /// </summary>
        internal static string _784 {
            get {
                return ResourceManager.GetString("_784", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TUNISIA.
        /// </summary>
        internal static string _788 {
            get {
                return ResourceManager.GetString("_788", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TURKEY.
        /// </summary>
        internal static string _792 {
            get {
                return ResourceManager.GetString("_792", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TURKMENISTAN.
        /// </summary>
        internal static string _795 {
            get {
                return ResourceManager.GetString("_795", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TURKS AND CAICOS ISLANDS.
        /// </summary>
        internal static string _796 {
            get {
                return ResourceManager.GetString("_796", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TUVALU.
        /// </summary>
        internal static string _798 {
            get {
                return ResourceManager.GetString("_798", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALBANIA.
        /// </summary>
        internal static string _8 {
            get {
                return ResourceManager.GetString("_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UGANDA.
        /// </summary>
        internal static string _800 {
            get {
                return ResourceManager.GetString("_800", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UKRAINE.
        /// </summary>
        internal static string _804 {
            get {
                return ResourceManager.GetString("_804", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FYRO MACEDONIA.
        /// </summary>
        internal static string _807 {
            get {
                return ResourceManager.GetString("_807", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EGYPT.
        /// </summary>
        internal static string _818 {
            get {
                return ResourceManager.GetString("_818", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNITED KINGDOM.
        /// </summary>
        internal static string _826 {
            get {
                return ResourceManager.GetString("_826", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUERNSEY.
        /// </summary>
        internal static string _831 {
            get {
                return ResourceManager.GetString("_831", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JERSEY.
        /// </summary>
        internal static string _832 {
            get {
                return ResourceManager.GetString("_832", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISLE OF MAN.
        /// </summary>
        internal static string _833 {
            get {
                return ResourceManager.GetString("_833", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TANZANIA.
        /// </summary>
        internal static string _834 {
            get {
                return ResourceManager.GetString("_834", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BELIZE.
        /// </summary>
        internal static string _84 {
            get {
                return ResourceManager.GetString("_84", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNITED STATES.
        /// </summary>
        internal static string _840 {
            get {
                return ResourceManager.GetString("_840", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIRGIN ISLANDS, U.S..
        /// </summary>
        internal static string _850 {
            get {
                return ResourceManager.GetString("_850", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BURKINA FASO.
        /// </summary>
        internal static string _854 {
            get {
                return ResourceManager.GetString("_854", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URUGUAY.
        /// </summary>
        internal static string _858 {
            get {
                return ResourceManager.GetString("_858", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BRITISH INDIAN OCEAN TERRITORY.
        /// </summary>
        internal static string _86 {
            get {
                return ResourceManager.GetString("_86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UZBEKISTAN.
        /// </summary>
        internal static string _860 {
            get {
                return ResourceManager.GetString("_860", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VENEZUELA.
        /// </summary>
        internal static string _862 {
            get {
                return ResourceManager.GetString("_862", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WALLIS AND FUTUNA.
        /// </summary>
        internal static string _876 {
            get {
                return ResourceManager.GetString("_876", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAMOA.
        /// </summary>
        internal static string _882 {
            get {
                return ResourceManager.GetString("_882", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YEMEN.
        /// </summary>
        internal static string _887 {
            get {
                return ResourceManager.GetString("_887", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERBIA AND MONTENEGRO.
        /// </summary>
        internal static string _891 {
            get {
                return ResourceManager.GetString("_891", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZAMBIA.
        /// </summary>
        internal static string _894 {
            get {
                return ResourceManager.GetString("_894", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOLOMON ISLANDS.
        /// </summary>
        internal static string _90 {
            get {
                return ResourceManager.GetString("_90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NON EU.
        /// </summary>
        internal static string _900 {
            get {
                return ResourceManager.GetString("_900", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PORTUGAL S.
        /// </summary>
        internal static string _901 {
            get {
                return ResourceManager.GetString("_901", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNITED KINGDOM S.
        /// </summary>
        internal static string _902 {
            get {
                return ResourceManager.GetString("_902", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FRANCE SS.
        /// </summary>
        internal static string _903 {
            get {
                return ResourceManager.GetString("_903", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KOSOVO.
        /// </summary>
        internal static string _904 {
            get {
                return ResourceManager.GetString("_904", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GERMANY S.
        /// </summary>
        internal static string _905 {
            get {
                return ResourceManager.GetString("_905", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CZECH REPUBLIC D.
        /// </summary>
        internal static string _906 {
            get {
                return ResourceManager.GetString("_906", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIRGIN ISLANDS, BRITISH.
        /// </summary>
        internal static string _92 {
            get {
                return ResourceManager.GetString("_92", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALDERNEY.
        /// </summary>
        internal static string _950 {
            get {
                return ResourceManager.GetString("_950", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AZORES.
        /// </summary>
        internal static string _951 {
            get {
                return ResourceManager.GetString("_951", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BALEARIC ISLANDS.
        /// </summary>
        internal static string _952 {
            get {
                return ResourceManager.GetString("_952", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBIZA.
        /// </summary>
        internal static string _953 {
            get {
                return ResourceManager.GetString("_953", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAJORCA.
        /// </summary>
        internal static string _954 {
            get {
                return ResourceManager.GetString("_954", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MENORCA.
        /// </summary>
        internal static string _955 {
            get {
                return ResourceManager.GetString("_955", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BUSINGEN.
        /// </summary>
        internal static string _956 {
            get {
                return ResourceManager.GetString("_956", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAMPIONE D&apos;ITALIA.
        /// </summary>
        internal static string _957 {
            get {
                return ResourceManager.GetString("_957", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANARY ISLANDS.
        /// </summary>
        internal static string _958 {
            get {
                return ResourceManager.GetString("_958", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FUERTEVENTUA.
        /// </summary>
        internal static string _959 {
            get {
                return ResourceManager.GetString("_959", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BRUNEI DARUSSALAM.
        /// </summary>
        internal static string _96 {
            get {
                return ResourceManager.GetString("_96", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRAN CANARIA.
        /// </summary>
        internal static string _960 {
            get {
                return ResourceManager.GetString("_960", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LANZAROTE.
        /// </summary>
        internal static string _961 {
            get {
                return ResourceManager.GetString("_961", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TENERIFE.
        /// </summary>
        internal static string _962 {
            get {
                return ResourceManager.GetString("_962", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEUTA.
        /// </summary>
        internal static string _963 {
            get {
                return ResourceManager.GetString("_963", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMMUNES OF LIVIGNO.
        /// </summary>
        internal static string _964 {
            get {
                return ResourceManager.GetString("_964", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISLE OF HELIGOLAND.
        /// </summary>
        internal static string _965 {
            get {
                return ResourceManager.GetString("_965", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MADEIRA.
        /// </summary>
        internal static string _966 {
            get {
                return ResourceManager.GetString("_966", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MELILLA.
        /// </summary>
        internal static string _967 {
            get {
                return ResourceManager.GetString("_967", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOUNT ATHOS.
        /// </summary>
        internal static string _968 {
            get {
                return ResourceManager.GetString("_968", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THE ITALIAN WATERS OF LAKE LUGANO.
        /// </summary>
        internal static string _969 {
            get {
                return ResourceManager.GetString("_969", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VATICAN CITY.
        /// </summary>
        internal static string _970 {
            get {
                return ResourceManager.GetString("_970", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANNEL ISLANDS.
        /// </summary>
        internal static string _999 {
            get {
                return ResourceManager.GetString("_999", resourceCulture);
            }
        }
    }
}
