//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JointRefundService.Domain
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SiteLocationCodeResponse", Namespace="http://schemas.datacontract.org/2004/07/JointRefundService.Domain")]
    public partial class SiteLocationCodeResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<int> CountryIdField;
        
        private bool MatchField;
        
        private System.Nullable<int> RetailerIdField;
        
        private System.Nullable<int> VoucherNumberField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CountryId
        {
            get
            {
                return this.CountryIdField;
            }
            set
            {
                this.CountryIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Match
        {
            get
            {
                return this.MatchField;
            }
            set
            {
                this.MatchField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> RetailerId
        {
            get
            {
                return this.RetailerIdField;
            }
            set
            {
                this.RetailerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> VoucherNumber
        {
            get
            {
                return this.VoucherNumberField;
            }
            set
            {
                this.VoucherNumberField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IPremierRefundVoucherService")]
public interface IPremierRefundVoucherService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPremierRefundVoucherService/IsVoucherRefunded", ReplyAction="http://tempuri.org/IPremierRefundVoucherService/IsVoucherRefundedResponse")]
    bool IsVoucherRefunded(int voucherId, int countryId, int retailerId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPremierRefundVoucherService/GetVoucherWithLocationCode", ReplyAction="http://tempuri.org/IPremierRefundVoucherService/GetVoucherWithLocationCodeRespons" +
        "e")]
    JointRefundService.Domain.SiteLocationCodeResponse GetVoucherWithLocationCode(string siteLocationCode);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IPremierRefundVoucherServiceChannel : IPremierRefundVoucherService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class PremierRefundVoucherServiceClient : System.ServiceModel.ClientBase<IPremierRefundVoucherService>, IPremierRefundVoucherService
{
    
    public PremierRefundVoucherServiceClient()
    {
    }
    
    public PremierRefundVoucherServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public PremierRefundVoucherServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public PremierRefundVoucherServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public PremierRefundVoucherServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public bool IsVoucherRefunded(int voucherId, int countryId, int retailerId)
    {
        return base.Channel.IsVoucherRefunded(voucherId, countryId, retailerId);
    }
    
    public JointRefundService.Domain.SiteLocationCodeResponse GetVoucherWithLocationCode(string siteLocationCode)
    {
        return base.Channel.GetVoucherWithLocationCode(siteLocationCode);
    }
}
